### PR TITLE
Careful reading

### LINKED ISSUE #1: Report errors if the temperature reading fails
Sometimes the temperature reading might fail and the file contents might look something like:

```
ff ff ff ff ff ff ff ff ff : crc=c9 NO
53 01 4b 46 7f ff 0d 10 e9 t=-62
```

or 

```
00 00 00 00 00 00 00 00 00 : crc=00 YES
00 00 00 00 00 00 00 00 00 t=0
```

Currently if this happens thermex will publish a `nil` value for the measurement, but that is not very helpful. It would be better to publish explicit failures. Perhaps after a prolonged period of failures we should remove the `Thermex.Monitor` actor that is trying to read that sensor since it has probably failed to been removed.

### PR DESCRIPTION
**Pull request by mmmries**
Fixes #1 

This splits the temperature parsing into its own module (with some tests) and switches the monitor to use the new parsing module. I also made it so that the monitor publishes failure messages in case you care about those.

I think we should bump the minor version for this change because if people were previously receiving these messages and just assuming that the second item in the tuple was a a float, their code might break since the second item in the tuple can now be an error tuple.

/cc @newellista @ztoolson

### CODE REVIEW

File: lib/thermex/monitor.ex [hunk 1]
```diff
@@ -31,29 +36,14 @@ defmodule Thermex.Monitor do
...
-    cond do
-      String.ends_with?(first_string, "YES") ->
-        String.split(second_string, "=")
-        |> List.last
-        |> Integer.parse
-      true ->
-        nil
-    end
+    filename
+    |> File.read!
```
Comment (ztoolson) [inline lib/thermex/monitor.ex:40]: Why did you change this from `stream!` to `read!`? Just wondering. I know that `read!` will load the whole file into memory, but maybe the file is small enough that this doesn't matter.

File: lib/thermex/parser.ex [hunk 2]
```diff
@@ -0,0 +1,23 @@
+defmodule Thermex.Parser do
+  def parse(reading) do
+    reading
+    |> String.strip
+    |> String.split("\n")
+    |> parse_temperature
+  end
+
+  defp parse_temperature(["00 00 00 00 00 00 00 00 00 : crc=00"<>_, _line2]) do
+    {:error, :untrusted_reading}
```
Comment (ztoolson) [inline lib/thermex/parser.ex:10]: :+1:

**Comment by ztoolson** [comment]
Changes look good to me. :+1:

**Comment by newellista** [comment]
:shipit:

File: lib/thermex/monitor.ex (hunk 1 above)
Comment (mmmries) [inline lib/thermex/monitor.ex:40]: The main reason I changed it was because I wanted to write some unit tests for parsing the contents and it was easier to write the test as passing in a string rather than a stream.
